create table stars (
	id integer,
	tyc character varying(100),
	gaia character varying(100),
	hyg character varying(100),
	hip character varying(100),
	hd character varying(100),
	hr character varying(100),
	gl character varying(100),
	bayer character varying(100),
	flam character varying(100),
	con character varying(100),
	proper character varying(100),
	ra numeric,
	decl numeric,
	pos_src character varying(100),
	dist numeric,
	x0 numeric,
	y0 numeric,
	z0 numeric,
	dist_src character varying(100),
	mag numeric,
	absmag numeric,
	mag_src character varying(100),
	rv numeric,
	rv_src character varying(100),
	pm_ra numeric,
	pm_dec numeric,
	pm_src character varying(100),
	vx numeric,
	vy numeric,
	vz numeric 
)
